---
- name: Run basic command on local hosts
  hosts: localhost               
  become: yes               
  tasks:
    - name: Test command
      shell: pwd
      register: result
 
    - name: Show the output
      debug:
        msg: "{{ result.stdout }}"
